server:
  port: 8081

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PROFILE-SERVICE
          #          uri: http://localhost:8083
          uri: lb://PROFILE-SERVICE
          predicates:
            - Path=/profile/**
        - id: USER-SERVICE
          uri: http://localhost:8082
#          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
        - id: POST-SERVICE
          #          uri: http://localhost:8084
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost